### ISSUE TITLE
Data version of web services

### ISSUE THREAD

**Issue by lo-ise** [PolarGeospatialCenter/comnap-antarctic-facilities#1]
Hi all, we're keen to use your Antarctic facilities OGC web services for the Antarctic Digital Database web map viewer (https://add.scar.org/). The viewer is currently using version 3.2.0 of the data, which we downloaded from here in 2019. 

I noticed the latest version of the data which you have made available to download is 3.3.0. However, it appears from the ArcGIS Online item (and I'm assuming the OGC services as well) is using version 3.0.1 of the data (2018). Is that correct? 

With thanks.

**Comment by Shane98c** [comment]
Thanks for catching this! I'll update this issue once we've got this sorted (likely the week after next).

**Comment by Shane98c** [comment]
@lo-ise Things should be synced up with the latest version now. I did notice some issues with the `last-modified` dates that I'll have to take a closer look at.

Let me know if you notice any issues!

https://web.overlord.pgc.umn.edu/arcgis/rest/services/reference/ant_comnap_antarctic_facilities/FeatureServer

**Comment by lo-ise** [comment]
Hi @Shane98c,

Thanks for your quick response. 

I tested the url you've linked here, and it re-directs to a PGC User login page. 

The link to the ArcGIS Item in `dist/readme.md` is pointing to the 2018 version, ie: Version 3.0.1: Released 08 August 2018. Is there a new ArcGIS item and OGC services for the 2020 data?

With thanks :)

**Comment by Shane98c** [comment]
My apologies, the url should be the same as the one in the Readme: https://overlord.pgc.umn.edu/arcgis/rest/services/reference/ant_comnap_antarctic_facilities/FeatureServer 

It looks like I'd missed one 2018 reference in the item description. This should be updated now. 

Thanks again for bringing this to our attention!
